### PR TITLE
Updated to reflect version change to 1.8.0b4

### PR DESCRIPTION
**Pull request by furritos**
Missed updating the version in this file.  Updating to conform to new version, 1.8.0b4.

### CODE REVIEW

**Comment by furritos** [comment]
Thanks again!  Also, one quick question... how does it work when it comes time to update the documentation @ pythonhosted?  Will you take care of that or is there a way I can contribute to it?

**Comment by beachmachine** [comment]
The documentation at pythonhosted is generated from the .rst within the docs folder. I do the upload as soon as i publish the new version of django-jython on PyPi. I think this will happen within the next few days.

**Comment by furritos** [comment]
Oh, that's good to know.  Thanks!

**Comment by beachmachine** [comment]
You're welcome!

**Pull request merged**
